# Generated by Django 3.2.7 on 2021-11-24 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='progarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
