# Generated by Django 3.2.7 on 2021-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0003_auto_20211125_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyPorgrams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
