# Generated by Django 3.2.7 on 2021-12-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0005_youthpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='monthlyPorgrams',
            new_name='MonthlyPrograms',
        ),
    ]
