# Generated by Django 3.2.7 on 2021-12-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0006_rename_monthlyporgrams_monthlyprograms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyPrograms',
            new_name='MonthlyProgram',
        ),
    ]
