# Generated by Django 3.2.7 on 2021-12-21 13:11

from django.db import migrations, models
import salamaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0007_rename_monthlyprograms_monthlyprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpost',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to=salamaapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to=salamaapp.models.filepath),
        ),
    ]
