# Generated by Django 3.2.7 on 2021-12-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0008_auto_20211221_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='April',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='December',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feburary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='March',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='November',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='October',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='September',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyProgram',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.RenameField(
            model_name='youthpost',
            old_name='iamge',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime),
        ),
    ]
