# Generated by Django 3.2.7 on 2021-12-22 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0010_alter_youthpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
