# Generated by Django 3.2.7 on 2022-02-05 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0013_auto_20220205_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploads',
            new_name='upload',
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 5, 17, 39, 45, 636726)),
        ),
    ]
