# Generated by Django 3.2.7 on 2022-02-05 16:58

import datetime
from django.db import migrations, models
import salamaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0014_auto_20220205_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to=salamaapp.models.filepath)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 5, 17, 58, 44, 374036))),
            ],
        ),
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 5, 17, 58, 44, 374036)),
        ),
    ]
