# Generated by Django 3.2.7 on 2022-02-15 10:06

import datetime
from django.db import migrations, models
import salamaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0020_auto_20220215_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorscorner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 11, 6, 10, 208630)),
        ),
        migrations.AddField(
            model_name='pastorscorner',
            name='image',
            field=models.ImageField(blank=True, upload_to=salamaapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='message',
            field=models.FileField(upload_to=salamaapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 11, 6, 10, 206631)),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='document',
            field=models.FileField(blank=True, upload_to=salamaapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 11, 6, 10, 205631)),
        ),
    ]
