# Generated by Django 3.2.7 on 2022-02-18 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0024_auto_20220215_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 21, 40, 1, 71964)),
        ),
        migrations.AlterField(
            model_name='pastorscorner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 21, 40, 1, 72963)),
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 21, 40, 1, 70964)),
        ),
    ]
