# Generated by Django 3.2.7 on 2022-02-18 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0025_auto_20220218_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 23, 9, 22, 56213)),
        ),
        migrations.AlterField(
            model_name='pastorscorner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 23, 9, 22, 57213)),
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 23, 9, 22, 55214)),
        ),
    ]
