# Generated by Django 3.2.7 on 2022-03-13 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamaapp', '0026_auto_20220218_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 16, 16, 55339)),
        ),
        migrations.AlterField(
            model_name='pastorscorner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 16, 16, 57336)),
        ),
        migrations.AlterField(
            model_name='youthpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 16, 16, 54342)),
        ),
    ]
